### ISSUE TITLE
Fx.CSS.search is buggy

### ISSUE THREAD

**Issue by ibolmo** [mootools/mootools-core#2215]
(from [Lighthouse](https://mootools.lighthouseapp.com/projects/2706/tickets/755-fxcsssearch-is-buggy))

Hi all,

I was playing with Element.morph when I encountered this problem,

when I define

``` css
.h36 { height:50px;
width:150px
}
```

$(element).morph('.h36') just works fine but,

``` css
.h36, .h35 { height:50px;
width:150px
}
```

$(element).morph('.h36') will fail to work

here are some example:
with simple selector: http://mooshell.net/vUxkJ/

with two selectors (fail to work): http://mooshell.net/sxUue/

a patched version I made: http://mooshell.net/QCmcv/

cheers
