### ISSUE TITLE
Fade in seems not work (IE 7-8)

### ISSUE THREAD

**Issue by Nek-** [mootools/mootools-core#2459]
Hello

There is a bug with the fade feature. But be careful: i'm not sure of this issue because I test on the version emulate by IE9.

I tryed to make a fade from something who have this CSS:

``` CSS
#navbar .background {
    position: absolute;
    background: #000000;
    opacity: 0.2;
    filter : alpha(opacity=20);
}
```

After fade in:

``` Javascript
$$('#navbar .background').fade('in');
```

On IE 7-8, the element is animated but the old opacity is reset after the animation.

That's not pretty cool. I imagine it's a bug.

Thanks for attention.
