### ISSUE TITLE
getCoordinates failure

### ISSUE THREAD

**Issue by ghost** [mootools/mootools-core#85]
``` css
element {
    left: 50%;
    margin-left: -10px;
}
```

``` javascript
element.getCoordinates(element.getOffsetParent());
```

fails, if "element" has a percentage as "left" value and a negative margin-left.
The calculated "left" value in pixel ignores the margin.

EDIT:

Demonstration using Drag from MooTools More:
http://jsfiddle.net/dHCXb/
